import XLSX from 'xlsx-js-style';
import type { AnalysisResult, LoggerAnalysis, LoggerData, RegressionModel } from '../types';
import { APP_VERSION, PRODUCT_NAME } from '../settings/defaults';
import { hourlyPlant, loggerSeries, plantSeries, scatterPlrEff, thin, toExcelDate } from '../charts/chartData';
import { analyzeLogger } from '../fluke/logger';
import { fmtDate, fmtTs } from '../utils/format';
import { KW_PER_TR } from '../calculations/units';
import { attachCharts, type ChartSpec, type SeriesSpec } from './chartxml';
import { predictorValue } from '../analysis/annualize';
import { chip, colLetter, q, Sheet, styles } from './sheet';

const DATE_FMT = 'yyyy-mm-dd hh:mm';
const PAL = ['0F7B8A', 'D9822B', '5B8C3A', '8E5BB5', 'C0392B', '2F6DB5', '9A7B1E', '4F5D75'];
const MAX_DATA_ROWS = 200000;

export interface ExportInput {
  analysis?: AnalysisResult | null;
  loggers: LoggerData[];
  /** Omit cached values (used by the formula verification test). */
  noCache?: boolean;
}

export interface ExportOutput { bytes: Uint8Array; fileName: string; sheets: string[]; }

const sanitize = (s: string) => s.replace(/[^A-Za-z0-9._-]+/g, '_');

export async function buildWorkbook(input: ExportInput): Promise<ExportOutput> {
  const a = input.analysis ?? null;
  const cache = !input.noCache;
  const loggerAnalyses = input.loggers.map((l) => ({ data: l, an: analyzeLogger(l) }));
  const sheets: Sheet[] = [];
  let charts: ChartSpec[] = [];

  if (a) {
    const hourly = hourlyPlant(a);
    const ph = plantHourlySheet(a, hourly);
    const summary = summarySheet(a, ph.refs, hourly.length, input.loggers.length > 0);
    const cd = new Sheet('Chart Data');
    charts = chartsFor(a, cd);
    const chartsSheet = new Sheet('Charts');
    chartsSheet.set(0, 0, 'Charts', styles.title);
    chartsSheet.set(1, 0, 'Native Excel charts. Source ranges are on the "Chart Data" sheet.', styles.sub);
    chartsSheet.widths = Array(20).fill(11);
    sheets.push(summary, chartsSheet, findingsSheet(a), chillersSheet(a), regressionSheet(a), ...(a.cdd ? [cddSheet(a)] : []), ...(a.weather ? [weatherSheet(a)] : []), ...(a.annual && a.annual.hourly ? [annualSheet(a)] : []), loadProfileSheet(a), ph.sheet, chillerDataSheet(a), cd);
    if (loggerAnalyses.length) {
      sheets.push(loggerSummarySheet(loggerAnalyses), loggerDataSheet(loggerAnalyses.map((x) => x.data), loggerAnalyses.map((x) => x.an)));
    }
  } else if (loggerAnalyses.length) {
    const { data, an } = loggerAnalyses[0];
    const cd = new Sheet('Chart Data');
    charts = loggerCharts(data, an, cd);
    const chartsSheet = new Sheet('Charts');
    chartsSheet.set(0, 0, 'Charts', styles.title);
    chartsSheet.set(1, 0, 'Native Excel charts. Source ranges are on the "Chart Data" sheet.', styles.sub);
    chartsSheet.widths = Array(20).fill(11);
    sheets.push(loggerSummarySheet(loggerAnalyses, true), chartsSheet, loggerFindingsSheet(loggerAnalyses), loggerDataSheet(loggerAnalyses.map((x) => x.data), loggerAnalyses.map((x) => x.an)), cd);
  } else throw new Error('Nothing to export – import BMS data or a logger file first.');

  const wb = XLSX.utils.book_new();
  for (const s of sheets) XLSX.utils.book_append_sheet(wb, s.build(cache), s.name);
  wb.Props = { Title: a ? 'Chiller Plant Analysis' : 'Chiller Power Profile', Author: PRODUCT_NAME, Comments: `Generated by ${PRODUCT_NAME} ${APP_VERSION}` };
  let bytes: Uint8Array = new Uint8Array(XLSX.write(wb, { type: 'array', bookType: 'xlsx', cellStyles: true }) as ArrayBuffer);
  const chartIdx = sheets.findIndex((s) => s.name === 'Charts');
  bytes = await attachCharts(bytes, chartIdx, charts);
  const fileName = a
    ? `Chiller_Plant_Analysis_${a.firstDate || 'undated'}.xlsx`
    : `Chiller_Power_Profile_${sanitize(loggerAnalyses[0].data.chiller)}_${fmtDate(loggerAnalyses[0].an.firstTs) || 'undated'}.xlsx`;
  return { bytes, fileName, sheets: sheets.map((s) => s.name) };
}

// ---------------------------------------------------------------- Plant Hourly
function plantHourlySheet(a: AnalysisResult, hourly: ReturnType<typeof hourlyPlant>) {
  const s = new Sheet('Plant Hourly');
  s.set(0, 0, 'Plant Hourly', styles.title);
  s.set(1, 0, 'Hourly aggregation of the plant rows that passed the filters. kW/TR is energy weighted: (Σ kWh) / (Σ TR·h).', styles.sub);
  const heads = ['Hour', 'Hours logged', 'Chillers kW (avg)', 'Plant TR (avg)', 'Aux kW (avg)', 'Chiller kWh', 'Aux kWh', 'TR·h', 'Peak TR', 'Plant kW/TR', 'Chiller kW/TR', 'ECWT °C', 'LCHWT °C', 'Target kW/TR'];
  s.head(3, 0, heads);
  const r0 = 4;
  hourly.forEach((h, i) => {
    const r = r0 + i;
    const x = r + 1;
    s.set(r, 0, toExcelDate(h.ts), styles.num, DATE_FMT);
    s.set(r, 1, h.hours, styles.num, '0.00');
    s.set(r, 2, h.chillerKW, styles.num, '#,##0.0');
    s.set(r, 3, h.planTR, styles.num, '#,##0.0');
    s.set(r, 4, h.auxKW, styles.num, '#,##0.0');
    s.set(r, 5, h.chillerKWh, styles.num, '#,##0.0');
    s.set(r, 6, h.auxKWh, styles.num, '#,##0.0');
    s.set(r, 7, h.trHours, styles.num, '#,##0.0');
    s.set(r, 8, h.peakTR, styles.num, '#,##0.0');
    s.set(r, 9, { f: `IF(H${x}>0,(F${x}+G${x})/H${x},"")`, v: h.trHours > 0 ? (h.chillerKWh + h.auxKWh) / h.trHours : '' }, styles.num, '0.000');
    s.set(r, 10, { f: `IF(H${x}>0,F${x}/H${x},"")`, v: h.trHours > 0 ? h.chillerKWh / h.trHours : '' }, styles.num, '0.000');
    s.set(r, 11, Number.isFinite(h.ecwt) ? h.ecwt : '', styles.num, '0.0');
    s.set(r, 12, Number.isFinite(h.lchwt) ? h.lchwt : '', styles.num, '0.0');
    s.set(r, 13, { f: 'Summary!$B$6', v: a.settings.targetKwPerTR }, styles.num, '0.00');
  });
  s.widths = [17, 11, 14, 13, 12, 12, 11, 11, 10, 12, 13, 9, 9, 12];
  const last = r0 + hourly.length; // Excel row number of last data row
  const rng = (c: number) => `${q(s.name)}!$${colLetter(c)}$${r0 + 1}:$${colLetter(c)}$${Math.max(last, r0 + 1)}`;
  return { sheet: s, refs: { hours: rng(1), chKWh: rng(5), auxKWh: rng(6), trh: rng(7), peak: rng(8) } };
}

// ---------------------------------------------------------------- Summary
function summarySheet(a: AnalysisResult, refs: Record<string, string>, nHours: number, hasLoggers: boolean) {
  const s = new Sheet('Summary');
  const k = a.kpis;
  const st = a.settings;
  s.set(0, 0, 'Chiller Plant Analysis', styles.title);
  s.set(1, 0, `Period ${a.firstDate} → ${a.lastDate}  ·  ${a.intervalMinutes} min interval  ·  ${a.exclusions.kept.toLocaleString('en-US')} of ${a.exclusions.total.toLocaleString('en-US')} rows analysed  ·  ${PRODUCT_NAME} ${APP_VERSION}`, styles.sub);
  s.set(2, 0, `${st.plantType === 'water' ? 'Water-cooled' : 'Air-cooled'} plant${hasLoggers ? ' · power from Fluke logger(s) where attached' : ''}`, styles.sub);
  s.set(4, 0, 'Inputs (editable – blue on yellow)', styles.section);
  s.set(4, 1, '', styles.section); s.set(4, 2, '', styles.section);
  // rows: 5 → Excel row 6 (target) , 6 → tariff, 7 → installed TR
  s.row(5, 0, ['Target plant kW/TR', { v: st.targetKwPerTR }, 'kW/TR'], styles.body);
  s.set(5, 1, st.targetKwPerTR, styles.input, '0.00');
  s.row(6, 0, [`Tariff`, null, `${st.currency}/kWh`], styles.body);
  s.set(6, 1, st.tariff, styles.input, '0.000');
  s.row(7, 0, ['Installed capacity', null, 'TR'], styles.body);
  s.set(7, 1, k.installedTR, styles.input, '#,##0');
  s.set(9, 0, 'Key performance indicators', styles.section);
  s.set(9, 1, '', styles.section); s.set(9, 2, '', styles.section); s.set(9, 3, '', styles.section);
  s.head(10, 0, ['KPI', 'Value', 'Unit', 'Basis']);
  const lab = (r: number, l: string) => s.set(r, 0, l, styles.label);
  let r = 11;
  const rows: Record<string, number> = {};
  const add = (key: string, label: string, f: string, v: number | string, unit: string, basis: string, z: string) => {
    lab(r, label);
    s.set(r, 1, { f, v }, styles.num, z);
    s.set(r, 2, unit, styles.body);
    s.set(r, 3, basis, styles.body);
    rows[key] = r + 1; // excel row
    r++;
  };
  const B = (key: string) => `B${rows[key]}`;
  add('ch', 'Chiller energy', `SUM(${refs.chKWh})`, k.chillerKWh, 'kWh', 'Σ chiller kW × interval', '#,##0');
  add('aux', 'Auxiliary energy', `SUM(${refs.auxKWh})`, k.auxKWh, 'kWh', 'aux kW per timestamp × interval', '#,##0');
  add('trh', 'Cooling delivered', `SUM(${refs.trh})`, k.trHours, 'TR·h', 'Σ plant TR × interval', '#,##0');
  add('hrs', 'Logged time', `SUM(${refs.hours})`, k.loggedHours, 'h', 'timestamps analysed × interval', '#,##0.0');
  add('th', 'Thermal energy', `${B('trh')}*${KW_PER_TR}`, k.thermalKWh, 'kWh thermal', 'TR·h × 3.51685', '#,##0');
  add('pk', 'Plant kW/TR', `(${B('ch')}+${B('aux')})/${B('trh')}`, k.plantKwPerTR, 'kW/TR', '(chiller kWh + aux kWh) / TR·h', '0.000');
  add('pc', 'Plant COP', `${KW_PER_TR}/${B('pk')}`, k.plantCOP, '–', '3.51685 / (kW/TR)', '0.00');
  add('ck', 'Chiller kW/TR', `${B('ch')}/${B('trh')}`, k.chillerKwPerTR, 'kW/TR', 'chiller kWh / TR·h', '0.000');
  add('cc', 'Chiller COP', `${KW_PER_TR}/${B('ck')}`, k.chillerCOP, '–', '3.51685 / (kW/TR)', '0.00');
  const bands = st.plantType === 'water' ? { p: [0.75, 0.9, 1.0], c: [0.6, 0.7, 0.85] } : { p: [1.15, 1.3, 1.45], c: [1.0, 1.2, 1.4] };
  const rateF = (cell: string, b: number[]) => `IF(${cell}<=${b[0]},"Excellent",IF(${cell}<=${b[1]},"Good",IF(${cell}<=${b[2]},"Fair","Needs improvement")))`;
  lab(r, 'Plant rating'); s.set(r, 1, { f: rateF(B('pk'), bands.p), v: k.plantRating }, chip(k.plantRating)); s.set(r, 2, '', styles.body); s.set(r, 3, `≤${bands.p.join(' / ≤')} kW/TR`, styles.body); r++;
  lab(r, 'Chiller rating'); s.set(r, 1, { f: rateF(B('ck'), bands.c), v: k.chillerRating }, chip(k.chillerRating)); s.set(r, 2, '', styles.body); s.set(r, 3, `≤${bands.c.join(' / ≤')} kW/TR`, styles.body); r++;
  add('as', 'Auxiliary share', `${B('aux')}/(${B('ch')}+${B('aux')})`, k.auxShare, '%', 'aux kWh / (chiller + aux kWh)', '0.0%');
  add('peak', 'Peak load', `MAX(${refs.peak})`, k.peakLoad, 'TR', 'highest interval plant TR', '#,##0');
  add('avg', 'Average load', `${B('trh')}/${B('hrs')}`, k.avgLoad, 'TR', 'TR·h / logged time', '#,##0');
  add('lf', 'Load factor', `${B('avg')}/${B('peak')}`, k.loadFactor, '%', 'average / peak', '0.0%');
  lab(r, 'Installed capacity'); s.set(r, 1, { f: 'B8', v: k.installedTR }, styles.num, '#,##0'); s.set(r, 2, 'TR', styles.body); s.set(r, 3, 'Σ rated TR of chillers analysed', styles.body); rows.inst = r + 1; r++;
  add('ka', 'Energy above target', `MAX(0,${B('ch')}+${B('aux')}-$B$6*${B('trh')})`, k.kWhAboveTarget, 'kWh', '(chiller + aux kWh) − target × TR·h', '#,##0');
  add('ca', 'Cost above target', `${B('ka')}*$B$7`, k.costAboveTarget, st.currency, 'kWh above target × tariff', '#,##0');
  add('an', 'Annualised cost above target', `${B('ca')}*8760/${B('hrs')}`, k.annualizedCost, `${st.currency}/yr`, 'scaled from logged period to 8 760 h', '#,##0');

  r += 1;
  s.set(r, 0, 'Row filtering', styles.section); s.set(r, 1, '', styles.section); s.set(r, 2, '', styles.section); s.set(r, 3, '', styles.section); r++;
  s.head(r++, 0, ['Reason', 'Rows', '', 'Rule']);
  const ex = a.exclusions;
  const line = (l: string, n: number, rule: string) => { s.row(r, 0, [l, null, '', rule], styles.body); s.set(r, 1, n, styles.num, '#,##0'); r++; };
  line('Total rows', ex.total, '');
  line('Non-numeric / missing', ex.reasons.nonNumeric, 'kW or cooling load could not be read');
  line('Bad timestamp', ex.reasons.badTimestamp, 'timestamp could not be parsed');
  line('kW ≤ 1', ex.reasons.lowPower, 'chiller off / no power');
  line(`Load ≤ rated × ${st.minPLR}`, ex.reasons.lowLoad, 'below minimum part-load ratio');
  line(`kW/TR outside ${st.outlierMin}–${st.outlierMax}`, st.outlierFilter ? ex.reasons.outlier : 0, st.outlierFilter ? 'outlier filter enabled' : 'outlier filter disabled');
  line('Rows excluded (distinct)', ex.excluded, 'a row may match several reasons');
  line('Rows analysed', ex.kept, '');
  if (a.warnings.length) {
    r++;
    s.set(r++, 0, 'Warnings', styles.section);
    for (const w of a.warnings) s.set(r++, 0, w, styles.wrap);
  }
  s.widths = [34, 16, 14, 46];
  return s;
}

// ---------------------------------------------------------------- Findings
function findingsSheet(a: AnalysisResult) {
  const s = new Sheet('Findings');
  s.set(0, 0, 'Findings & energy-saving opportunities', styles.title);
  s.set(1, 0, 'Savings are indicative estimates from the stated assumptions – verify before committing to a project.', styles.sub);
  s.head(3, 0, ['#', 'Status', 'Finding', 'Explanation', 'Key numbers', 'Est. savings (kWh)', `Est. savings (${a.settings.currency})`]);
  a.findings.forEach((f, i) => {
    const r = 4 + i;
    s.set(r, 0, i + 1, styles.num);
    s.set(r, 1, f.status, chip(f.status));
    s.set(r, 2, f.title, styles.label);
    s.set(r, 3, f.text, styles.wrap);
    s.set(r, 4, f.numbers.map((n) => `${n.label}: ${n.value}`).join('\n'), styles.wrap);
    s.set(r, 5, f.savingsKWh ?? '', styles.num, '#,##0');
    s.set(r, 6, f.savingsCost ?? '', styles.num, '#,##0');
  });
  s.widths = [5, 11, 32, 70, 42, 16, 16];
  return s;
}

// ---------------------------------------------------------------- Chillers
function chillersSheet(a: AnalysisResult) {
  const s = new Sheet('Chillers');
  s.set(0, 0, 'Chiller comparison', styles.title);
  s.set(1, 0, 'Status: ≤5 % above rated = On spec · ≤12 % = Degraded · ≤25 % = Poor · otherwise Investigate.   * IPLV point outside measured ECWT ±0.5 °C or PLR ±0.05 (extrapolated).', styles.sub);
  s.head(3, 0, ['Chiller', 'Rated TR', 'Rated kW/TR', 'Run hours', 'TR·h', 'kWh', 'Avg PLR', 'kW/TR', 'COP', 'P10 kW/TR', 'P90 kW/TR', '% vs rated', 'Avg ΔT °C', 'IPLV kW/TR', 'IPLV COP', 'Status']);
  a.chillers.forEach((c, i) => {
    const r = 4 + i;
    const x = r + 1;
    s.set(r, 0, c.id, styles.label);
    s.set(r, 1, c.ratedTR, styles.num, '#,##0');
    s.set(r, 2, c.ratedKwPerTR, styles.num, '0.000');
    s.set(r, 3, c.runHours, styles.num, '#,##0.0');
    s.set(r, 4, c.trHours, styles.num, '#,##0');
    s.set(r, 5, c.kWh, styles.num, '#,##0');
    s.set(r, 6, c.avgPLR, styles.num, '0.0%');
    s.set(r, 7, { f: `F${x}/E${x}`, v: c.kwPerTR }, styles.num, '0.000');
    s.set(r, 8, { f: `${KW_PER_TR}/H${x}`, v: c.cop }, styles.num, '0.00');
    s.set(r, 9, c.p10, styles.num, '0.000');
    s.set(r, 10, c.p90, styles.num, '0.000');
    s.set(r, 11, { f: `H${x}/C${x}-1`, v: c.pctVsRated / 100 }, styles.num, '0.0%');
    s.set(r, 12, Number.isFinite(c.avgDeltaT) ? c.avgDeltaT : '', styles.num, '0.00');
    const star = c.iplv?.extrapolated ? '"*"' : '';
    s.set(r, 13, c.iplv && Number.isFinite(c.iplv.iplvKwPerTR) ? c.iplv.iplvKwPerTR : 'n/a', styles.num, `0.000${star}`);
    s.set(r, 14, c.iplv && Number.isFinite(c.iplv.iplvCOP) ? c.iplv.iplvCOP : 'n/a', styles.num, `0.00${star}`);
    s.set(r, 15, c.status, chip(c.status));
  });
  let r = 6 + a.chillers.length;
  const withIplv = a.chillers.filter((c) => c.iplv);
  if (withIplv.length) {
    s.set(r++, 0, 'IPLV rating points (multivariate model)', styles.section);
    s.head(r++, 0, ['Chiller', 'PLR', 'ECWT °C', 'Weight', 'TR', 'kW', 'kW/TR', 'COP', 'Outside measured range']);
    for (const c of withIplv) for (const p of c.iplv!.points) {
      s.row(r, 0, [c.id, null, null, null, null, null, null, null, p.outOfRange ? '*' : ''], styles.body);
      s.set(r, 1, p.plr, styles.num, '0%'); s.set(r, 2, p.ecwt, styles.num, '0.00'); s.set(r, 3, p.weight, styles.num, '0.00');
      s.set(r, 4, p.tr, styles.num, '#,##0'); s.set(r, 5, p.kW, styles.num, '#,##0.0'); s.set(r, 6, p.kwPerTR, styles.num, '0.000'); s.set(r, 7, p.cop, styles.num, '0.00');
      r++;
    }
    s.set(r + 1, 0, 'IPLV = 1 / Σ(wi / COPi), LCHWT 6.67 °C. Weights 1 % / 42 % / 45 % / 12 % at 100 / 75 / 50 / 25 % PLR.', styles.sub);
  }
  s.widths = [12, 10, 12, 11, 12, 12, 10, 10, 9, 11, 11, 11, 10, 12, 10, 13];
  return s;
}

// ---------------------------------------------------------------- Regression
function modelBlock(s: Sheet, r: number, m: RegressionModel, selected: boolean) {
  s.set(r, 0, `${m.kind[0].toUpperCase()}${m.kind.slice(1)} model${selected ? '  ◄ selected' : ''}`, styles.label);
  s.row(r, 1, [`n = ${m.n}`, `R² = ${m.r2.toFixed(4)}`, `Adj R² = ${m.adjR2.toFixed(4)}`, `RMSE = ${m.rmse.toFixed(2)} kW`], styles.body);
  r++;
  s.head(r++, 0, ['Term', 'Coefficient', 'Std error', 't', 'p-value', '95 % CI low', '95 % CI high', 'Significant']);
  for (const c of m.coefs) {
    s.set(r, 0, c.name, styles.body);
    s.set(r, 1, c.value, styles.num, '0.000000'); s.set(r, 2, c.se, styles.num, '0.000000'); s.set(r, 3, c.t, styles.num, '0.00');
    s.set(r, 4, c.p, styles.num, '0.0000'); s.set(r, 5, c.ciLow, styles.num, '0.000000'); s.set(r, 6, c.ciHigh, styles.num, '0.000000');
    s.set(r, 7, c.significant ? 'Yes' : 'No', styles.body);
    r++;
  }
  return r + 1;
}
function regressionSheet(a: AnalysisResult) {
  const s = new Sheet('Regression');
  s.set(0, 0, 'Regression analysis (OLS, ASHRAE Guideline 14)', styles.title);
  s.set(1, 0, 'kW = f(Q[TR], ECWT, LCHWT). Predictors standardised for fitting; coefficients and covariance back-transformed to original units. Student-t 95 % intervals.', styles.sub);
  let r = 3;
  const subjects = [...(a.plantRegression ? [a.plantRegression] : []), ...a.chillerRegressions];
  for (const reg of subjects) {
    s.set(r, 0, reg.subject === 'Plant' ? 'Plant (chillers + auxiliaries)' : `Chiller ${reg.subject}`, styles.section);
    for (let c = 1; c < 10; c++) s.set(r, c, '', styles.section);
    r++;
    if (!reg.models.length) { s.set(r++, 0, reg.notes.join(' '), styles.sub); r++; continue; }
    s.head(r++, 0, ['Model', 'n', 'R²', 'Adj R²', 'RMSE (kW)', 'CV(RMSE) %', 'NMBE %', 'Guideline 14', 'Selected']);
    for (const m of reg.models) {
      s.set(r, 0, m.kind, styles.label); s.set(r, 1, m.n, styles.num, '0'); s.set(r, 2, m.r2, styles.num, '0.0000'); s.set(r, 3, m.adjR2, styles.num, '0.0000');
      s.set(r, 4, m.rmse, styles.num, '0.00'); s.set(r, 5, m.cv, styles.num, '0.00'); s.set(r, 6, m.nmbe, styles.num, '0.000');
      const v = m.guideline14.pass ? 'PASS' : 'FAIL';
      s.set(r, 7, v, chip(v)); s.set(r, 8, m === reg.selected ? '◄' : '', styles.body);
      r++;
    }
    s.set(r++, 0, `Limits: CV ≤ ${reg.models[0].guideline14.cvLimit} %, |NMBE| ≤ ${reg.models[0].guideline14.nmbeLimit} % (${a.intervalMinutes <= 60 ? 'hourly-or-finer' : 'coarser than hourly'} data).${reg.notes.length ? '  ' + reg.notes.join(' ') : ''}`, styles.sub);
    r++;
    for (const m of reg.models) r = modelBlock(s, r, m, m === reg.selected);
    r++;
  }
  s.widths = [22, 14, 14, 12, 12, 14, 14, 14, 10, 4];
  return s;
}

// ---------------------------------------------------------------- Load profile
function loadProfileSheet(a: AnalysisResult) {
  const s = new Sheet('Load Profile');
  s.set(0, 0, 'Load profile', styles.title);
  s.set(1, 0, 'Plant load as % of installed capacity; chiller bins by PLR. kW/TR = Σ kWh / Σ TR·h within each bin.', styles.sub);
  let r = 3;
  const block = (title: string, bins: AnalysisResult['loadProfile'], includeAux: boolean) => {
    s.set(r++, 0, title, styles.section);
    s.head(r++, 0, ['Bin', 'Hours', 'TR·h', 'kWh', 'kW/TR', '% of time']);
    const first = r + 1;
    const lastRow = r + bins.length;
    bins.forEach((b) => {
      const x = r + 1;
      s.set(r, 0, b.label, styles.label); s.set(r, 1, b.hours, styles.num, '#,##0.0'); s.set(r, 2, b.trHours, styles.num, '#,##0'); s.set(r, 3, b.kWh, styles.num, '#,##0');
      s.set(r, 4, { f: `IF(C${x}>0,D${x}/C${x},"")`, v: b.trHours > 0 ? b.kWh / b.trHours : '' }, styles.num, '0.000');
      const tot = bins.reduce((t, y) => t + y.hours, 0);
      s.set(r, 5, { f: `IF(SUM(B$${first}:B$${lastRow})>0,B${x}/SUM(B$${first}:B$${lastRow}),0)`, v: tot > 0 ? b.hours / tot : 0 }, styles.num, '0.0%');
      r++;
    });
    if (includeAux) s.set(r, 0, 'Plant bins include auxiliary energy.', styles.sub);
    r += 2;
  };
  block('Plant load profile (% of installed TR)', a.loadProfile, true);
  for (const c of a.chillers) block(`Chiller ${c.id} – PLR bins`, a.chillerPlrBins[c.id], false);
  s.widths = [16, 11, 12, 12, 10, 11];
  return s;
}

// ---------------------------------------------------------------- Chiller Data
function chillerDataSheet(a: AnalysisResult) {
  const s = new Sheet('Chiller Data');
  s.set(0, 0, 'Chiller data (rows used in the analysis)', styles.title);
  const rows = a.chillerRows.length > MAX_DATA_ROWS ? thin(a.chillerRows, MAX_DATA_ROWS) : a.chillerRows;
  s.set(1, 0, rows.length < a.chillerRows.length ? `Showing ${rows.length.toLocaleString('en-US')} of ${a.chillerRows.length.toLocaleString('en-US')} rows (evenly thinned for file size).` : `${rows.length.toLocaleString('en-US')} rows.`, styles.sub);
  s.head(3, 0, ['Timestamp', 'Chiller', 'kW', 'TR', 'kW/TR', 'Rated TR', 'PLR', 'ECWT °C', 'LCHWT °C', 'ECHWT °C', 'Aux kW']);
  rows.forEach((d, i) => {
    const r = 4 + i, x = r + 1;
    s.set(r, 0, toExcelDate(d.ts), styles.num, DATE_FMT); s.set(r, 1, d.chiller, styles.body);
    s.set(r, 2, d.kW, styles.num, '#,##0.0'); s.set(r, 3, d.load, styles.num, '#,##0.0');
    s.set(r, 4, { f: `C${x}/D${x}`, v: d.kwPerTR }, styles.num, '0.000');
    s.set(r, 5, d.ratedTR, styles.num, '#,##0');
    s.set(r, 6, { f: `D${x}/F${x}`, v: d.plr }, styles.num, '0.0%');
    s.set(r, 7, Number.isFinite(d.ecwt) ? d.ecwt : '', styles.num, '0.0'); s.set(r, 8, Number.isFinite(d.lchwt) ? d.lchwt : '', styles.num, '0.0');
    s.set(r, 9, Number.isFinite(d.echwt) ? d.echwt : '', styles.num, '0.0'); s.set(r, 10, Number.isFinite(d.aux) ? d.aux : '', styles.num, '#,##0.0');
  });
  s.widths = [17, 10, 10, 10, 9, 9, 8, 9, 9, 9, 9];
  return s;
}

// ---------------------------------------------------------------- Chart Data + chart specs
function chartsFor(a: AnalysisResult, cd: Sheet): ChartSpec[] {
  cd.set(0, 0, 'Chart Data', styles.title);
  cd.set(1, 0, 'Source ranges for the charts on the Charts sheet (thinned for size).', styles.sub);
  const HEAD = 3;
  let col = 0;
  const charts: ChartSpec[] = [];
  const ref = (c: number, n: number) => `${q(cd.name)}!$${colLetter(c)}$${HEAD + 2}:$${colLetter(c)}$${HEAD + 1 + n}`;
  const put = (c: number, header: string, vals: (number | string)[], z?: string) => {
    cd.set(HEAD, c, header, styles.head);
    vals.forEach((v, i) => cd.set(HEAD + 1 + i, c, v, styles.num, z));
  };
  const pos = (i: number): [number, number, number, number] => [(i % 2) * 10, 3 + Math.floor(i / 2) * 21, (i % 2) * 10 + 9, 3 + Math.floor(i / 2) * 21 + 20];

  // 1: kW/TR vs PLR
  const pts = scatterPlrEff(a, 4000);
  const ids = a.chillers.map((c) => c.id).slice(0, 8);
  const s1: SeriesSpec[] = [];
  ids.forEach((id, i) => {
    const p = thin(pts.filter((x) => x.chiller === id), 600);
    if (!p.length) return;
    put(col, `${id} PLR`, p.map((x) => x.plr), '0.000'); put(col + 1, `${id} kW/TR`, p.map((x) => x.eff), '0.000');
    s1.push({ name: id, xRef: ref(col, p.length), yRef: ref(col + 1, p.length), xVals: p.map((x) => x.plr), yVals: p.map((x) => x.eff), color: PAL[i % PAL.length] });
    col += 2;
  });
  charts.push({ title: 'kW/TR vs part-load ratio', type: 'scatter', xTitle: 'PLR', yTitle: 'kW/TR', xFormat: '0.0', yFormat: '0.00', xMin: 0, series: s1, anchor: pos(0) });

  // 2: kW/TR vs ECWT
  const withE = pts.filter((p) => Number.isFinite(p.ecwt));
  if (withE.length > 3) {
    const p = thin(withE, 1500);
    put(col, 'ECWT °C', p.map((x) => x.ecwt), '0.0'); put(col + 1, 'kW/TR (ECWT)', p.map((x) => x.eff), '0.000');
    charts.push({ title: 'kW/TR vs entering condenser-water temperature', type: 'scatter', xTitle: 'ECWT / OAT (°C)', yTitle: 'kW/TR', xFormat: '0', yFormat: '0.00',
      series: [{ name: 'Chiller intervals', xRef: ref(col, p.length), yRef: ref(col + 1, p.length), xVals: p.map((x) => x.ecwt), yVals: p.map((x) => x.eff), color: PAL[0] }], anchor: pos(charts.length) });
    col += 2;
  }

  // 3/4: time series
  const ps = plantSeries(a, 1000);
  put(col, 'Date', ps.map((x) => toExcelDate(x.ts)), DATE_FMT);
  put(col + 1, 'Plant TR', ps.map((x) => x.tr), '#,##0');
  put(col + 2, 'Plant kW/TR', ps.map((x) => (Number.isFinite(x.kwPerTR) ? x.kwPerTR : '') as number), '0.000');
  put(col + 3, 'Chiller kW/TR', ps.map((x) => (Number.isFinite(x.chillerKwPerTR) ? x.chillerKwPerTR : '') as number), '0.000');
  put(col + 4, 'Target kW/TR', ps.map(() => a.settings.targetKwPerTR), '0.00');
  const xs = ps.map((x) => toExcelDate(x.ts));
  charts.push({ title: 'Plant load', type: 'scatter', xTitle: 'Date', yTitle: 'TR', xFormat: 'dd-mmm', yFormat: '#,##0', yMin: 0,
    series: [{ name: 'Plant TR', xRef: ref(col, ps.length), yRef: ref(col + 1, ps.length), xVals: xs, yVals: ps.map((x) => x.tr), color: PAL[0], kind: 'line' }], anchor: pos(charts.length) });
  charts.push({ title: 'Plant & chiller efficiency', type: 'scatter', xTitle: 'Date', yTitle: 'kW/TR', xFormat: 'dd-mmm', yFormat: '0.00', yMin: 0,
    series: [
      { name: 'Plant kW/TR', xRef: ref(col, ps.length), yRef: ref(col + 2, ps.length), xVals: xs, yVals: ps.map((x) => x.kwPerTR), color: PAL[1], kind: 'line' },
      { name: 'Chiller kW/TR', xRef: ref(col, ps.length), yRef: ref(col + 3, ps.length), xVals: xs, yVals: ps.map((x) => x.chillerKwPerTR), color: PAL[0], kind: 'line' },
      { name: 'Target', xRef: ref(col, ps.length), yRef: ref(col + 4, ps.length), xVals: xs, yVals: ps.map(() => a.settings.targetKwPerTR), color: PAL[4], kind: 'line', dash: true },
    ], anchor: pos(charts.length) });
  col += 5;

  // 5: load profile
  put(col, 'Load bin', a.loadProfile.map((b) => b.label) as unknown as number[]); put(col + 1, 'Hours', a.loadProfile.map((b) => b.hours), '#,##0.0');
  charts.push({ title: 'Load profile – hours by % of installed capacity', type: 'bar', xTitle: 'Plant load bin', yTitle: 'Hours', yFormat: '#,##0', yMin: 0,
    series: [{ name: 'Hours', xRef: ref(col, 10), yRef: ref(col + 1, 10), xVals: a.loadProfile.map((b) => b.label), yVals: a.loadProfile.map((b) => b.hours), color: PAL[0] }], anchor: pos(charts.length) });
  col += 2;

  // 6: chiller comparison
  if (a.chillers.length) {
    const n = a.chillers.length;
    put(col, 'Chiller', a.chillers.map((c) => c.id) as unknown as number[]); put(col + 1, 'Actual kW/TR', a.chillers.map((c) => c.kwPerTR), '0.000'); put(col + 2, 'Rated kW/TR', a.chillers.map((c) => c.ratedKwPerTR), '0.000');
    charts.push({ title: 'Chiller comparison – actual vs rated kW/TR', type: 'bar', xTitle: 'Chiller', yTitle: 'kW/TR', yFormat: '0.00', yMin: 0,
      series: [
        { name: 'Actual', xRef: ref(col, n), yRef: ref(col + 1, n), xVals: a.chillers.map((c) => c.id), yVals: a.chillers.map((c) => c.kwPerTR), color: PAL[1] },
        { name: 'Rated', xRef: ref(col, n), yRef: ref(col + 2, n), xVals: a.chillers.map((c) => c.id), yVals: a.chillers.map((c) => c.ratedKwPerTR), color: PAL[0] },
      ], anchor: pos(charts.length) });
    col += 3;
  }
  // 7/8: customer CDD – daily energy vs CDD (with the fitted line) and actual vs weather-expected
  const cdd = a.cdd;
  if (cdd && cdd.energyModel) {
    const u = cdd.days.filter((d) => d.used);
    const lo = Math.min(...u.map((d) => d.cdd as number)), hi = Math.max(...u.map((d) => d.cdd as number));
    const fit = [lo, hi].map((x) => cdd.energyModel!.predict(x));
    put(col, 'CDD', u.map((d) => d.cdd as number), '0.0'); put(col + 1, 'Daily kWh', u.map((d) => d.kWh), '#,##0');
    put(col + 2, 'Fit CDD', [lo, hi], '0.0'); put(col + 3, 'Fit kWh', fit, '#,##0');
    charts.push({ title: 'Daily plant energy vs cooling degree days', type: 'scatter', xTitle: 'CDD', yTitle: 'kWh/day', xFormat: '0', yFormat: '#,##0', yMin: 0,
      series: [
        { name: 'Days', xRef: ref(col, u.length), yRef: ref(col + 1, u.length), xVals: u.map((d) => d.cdd as number), yVals: u.map((d) => d.kWh), color: PAL[0] },
        { name: `Fit (R² ${cdd.energyModel.r2.toFixed(2)})`, xRef: ref(col + 2, 2), yRef: ref(col + 3, 2), xVals: [lo, hi], yVals: fit, color: PAL[4], kind: 'line' },
      ], anchor: pos(charts.length) });
    col += 4;
    const dts = u.map((d) => toExcelDate(d.day));
    put(col, 'Date', dts, 'dd-mmm'); put(col + 1, 'Actual kWh', u.map((d) => d.kWh), '#,##0'); put(col + 2, 'Expected kWh', u.map((d) => d.expectedKWh as number), '#,##0');
    charts.push({ title: 'Daily energy – actual vs weather-expected', type: 'scatter', xTitle: 'Date', yTitle: 'kWh/day', xFormat: 'dd-mmm', yFormat: '#,##0', yMin: 0,
      series: [
        { name: 'Actual', xRef: ref(col, u.length), yRef: ref(col + 1, u.length), xVals: dts, yVals: u.map((d) => d.kWh), color: PAL[1], kind: 'both' },
        { name: 'Expected from CDD', xRef: ref(col, u.length), yRef: ref(col + 2, u.length), xVals: dts, yVals: u.map((d) => d.expectedKWh as number), color: PAL[0], kind: 'line', dash: true },
      ], anchor: pos(charts.length) });
    col += 3;
  }
  // 9-11: customer hourly weather – plant kW and kW/TR against temperature, kW against enthalpy
  const wx = a.weather;
  if (wx && wx.selected) {
    const u = thin(wx.rows.filter((r) => r.used && r.tempC !== null), 1200);
    put(col, 'Temp °C', u.map((r) => r.tempC as number), '0.0'); put(col + 1, 'kW', u.map((r) => r.kW), '#,##0'); put(col + 2, 'kW/TR', u.map((r) => (Number.isFinite(r.kwPerTR) ? r.kwPerTR : '') as number), '0.000');
    charts.push({ title: 'Hourly plant kW vs outdoor temperature', type: 'scatter', xTitle: 'Dry-bulb temperature (°C)', yTitle: 'kW', xFormat: '0', yFormat: '#,##0', yMin: 0,
      series: [{ name: 'Hours', xRef: ref(col, u.length), yRef: ref(col + 1, u.length), xVals: u.map((r) => r.tempC as number), yVals: u.map((r) => r.kW), color: PAL[0] }], anchor: pos(charts.length) });
    charts.push({ title: 'Hourly plant kW/TR vs outdoor temperature', type: 'scatter', xTitle: 'Dry-bulb temperature (°C)', yTitle: 'kW/TR', xFormat: '0', yFormat: '0.00', yMin: 0,
      series: [{ name: 'Hours', xRef: ref(col, u.length), yRef: ref(col + 2, u.length), xVals: u.map((r) => r.tempC as number), yVals: u.map((r) => r.kwPerTR), color: PAL[3] }], anchor: pos(charts.length) });
    col += 3;
    const e = u.filter((r) => r.enthalpy !== null);
    if (e.length > 3) {
      put(col, 'Enthalpy kJ/kg', e.map((r) => r.enthalpy as number), '0.0'); put(col + 1, 'kW (enthalpy)', e.map((r) => r.kW), '#,##0');
      charts.push({ title: 'Hourly plant kW vs enthalpy', type: 'scatter', xTitle: 'Enthalpy (kJ/kg)', yTitle: 'kW', xFormat: '0', yFormat: '#,##0', yMin: 0,
        series: [{ name: 'Hours', xRef: ref(col, e.length), yRef: ref(col + 1, e.length), xVals: e.map((r) => r.enthalpy as number), yVals: e.map((r) => r.kW), color: PAL[1] }], anchor: pos(charts.length) });
      col += 2;
    }
  }
  // 12: annual projection – monthly energy by method
  const an = a.annual;
  if (an && (an.hourly || an.daily)) {
    const MON = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    put(col, 'Month', MON as unknown as number[]);
    const series: SeriesSpec[] = [];
    let k = col + 1;
    for (const m of [an.hourly, an.daily]) {
      if (!m) continue;
      put(k, `kWh (${m.method})`, m.monthly.map((x) => x.kWh), '#,##0');
      series.push({ name: `${m.method[0].toUpperCase()}${m.method.slice(1)} method`, xRef: ref(col, 12), yRef: ref(k, 12), xVals: MON, yVals: m.monthly.map((x) => x.kWh), color: PAL[series.length] });
      k++;
    }
    charts.push({ title: 'Projected monthly energy (typical year)', type: 'bar', xTitle: 'Month', yTitle: 'kWh', yFormat: '#,##0', yMin: 0, series, anchor: pos(charts.length) });
    col = k;
  }
  cd.widths = Array(col + 1).fill(14);
  return charts;
}

// ---------------------------------------------------------------- hourly weather sheet
function weatherSheet(a: AnalysisResult) {
  const w = a.weather!;
  const s = new Sheet('Weather Hourly');
  s.set(0, 0, 'Hourly weather – plant power vs temperature, enthalpy and humidity', styles.title);
  s.set(1, 0, `Weather file: ${w.fileName}. Hourly data ⇒ Guideline 14 limits CV ≤ 30 %, |NMBE| ≤ 10 %. Only hours with the plant running are used unless set otherwise.`, styles.sub);
  const sel = w.selected;
  let r = 3;
  if (sel) {
    s.head(r++, 0, ['Predictors', 'n', 'R²', 'Adj R²', 'RMSE kW', 'CV(RMSE) %', 'NMBE %', 'Guideline 14', 'Selected']);
    for (const c of w.candidates) {
      const m = c.energy;
      s.set(r, 0, c.label, styles.label); s.set(r, 1, m.n, styles.num, '0'); s.set(r, 2, m.r2, styles.num, '0.0000'); s.set(r, 3, m.adjR2, styles.num, '0.0000');
      s.set(r, 4, m.rmse, styles.num, '0.0'); s.set(r, 5, m.cv, styles.num, '0.00'); s.set(r, 6, m.nmbe, styles.num, '0.000');
      const v = m.guideline14.pass ? 'PASS' : 'FAIL';
      s.set(r, 7, v, chip(v)); s.set(r, 8, c === sel ? '◄' : '', styles.body);
      r++;
    }
    r++;
    // selected-model coefficients – fixed cells referenced by the hourly formulas below
    const coefRow = r;
    s.set(r++, 0, `Selected model: ${sel.label}   (kW = b0 + b1·${sel.id === 'enthalpy' ? 'h' : 'T'}${sel.id === 'temperature+humidity' ? ' + b2·RH' : ''})`, styles.section);
    s.set(r - 1, 1, '', styles.section); s.set(r - 1, 2, '', styles.section);
    sel.energy.coefs.forEach((k, i) => { s.set(r, 0, i === 0 ? 'b0 (intercept)' : `b${i} (${k.name})`, styles.label); s.set(r, 1, k.value, styles.num, '0.000000'); s.set(r, 2, `95 % CI ${k.ciLow.toPrecision(4)} … ${k.ciHigh.toPrecision(4)}`, styles.body); r++; });
    if (w.normalised && w.reference) {
      s.set(r, 0, 'Plant kW at mean weather', styles.label); s.set(r, 1, w.normalised.kW, styles.num, '#,##0'); r++;
      s.set(r, 0, 'Cooling load at mean weather (TR)', styles.label); s.set(r, 1, w.normalised.tr, styles.num, '#,##0'); r++;
      s.set(r, 0, 'Plant kW/TR at mean weather', styles.label); s.set(r, 1, { f: `IF(B${r}>0,B${r - 1}/B${r},"")`, v: w.normalised.kwPerTR }, styles.num, '0.000'); r++;
    }
    r++;
    const binBlock = (title: string, bins: NonNullable<typeof w.enthalpyBins>) => {
      s.set(r++, 0, title, styles.section); s.set(r - 1, 1, '', styles.section); s.set(r - 1, 2, '', styles.section);
      s.head(r++, 0, ['Bin', 'Hours', 'Avg kW', 'Avg TR', 'kW/TR']);
      for (const b of bins) {
        const x = r + 1;
        s.set(r, 0, b.label, styles.label); s.set(r, 1, b.hours, styles.num, '#,##0'); s.set(r, 2, b.avgKW, styles.num, '#,##0'); s.set(r, 3, b.avgTR, styles.num, '#,##0');
        s.set(r, 4, { f: `IF(D${x}>0,C${x}/D${x},"")`, v: b.avgTR > 0 ? b.avgKW / b.avgTR : '' }, styles.num, '0.000');
        r++;
      }
      r++;
    };
    binBlock('Temperature bins (2 °C)', w.tempBins);
    if (w.enthalpyBins) binBlock('Enthalpy bins (5 kJ/kg)', w.enthalpyBins);
    // hourly table
    const h0 = r;
    s.head(h0, 0, ['Hour', 'Temp °C', 'RH %', 'Enthalpy kJ/kg', 'Plant kW', 'Plant TR', 'kW/TR', 'Used', 'Expected kW', 'Residual kW']);
    w.rows.forEach((d, i) => {
      const rr = h0 + 1 + i;
      const x = rr + 1;
      s.set(rr, 0, toExcelDate(d.ts), styles.num, DATE_FMT);
      s.set(rr, 1, d.tempC ?? '', styles.num, '0.0'); s.set(rr, 2, d.rh ?? '', styles.num, '0'); s.set(rr, 3, d.enthalpy ?? '', styles.num, '0.0');
      s.set(rr, 4, d.kW, styles.num, '#,##0'); s.set(rr, 5, d.tr, styles.num, '#,##0');
      s.set(rr, 6, { f: `IF(F${x}>0,E${x}/F${x},"")`, v: d.tr > 0 ? d.kW / d.tr : '' }, styles.num, '0.000');
      s.set(rr, 7, d.used ? 1 : 0, styles.num, '0');
      const b0 = `$B$${coefRow + 2}`, b1 = `$B$${coefRow + 3}`, b2 = `$B$${coefRow + 4}`;
      const expr = sel.id === 'enthalpy' ? `${b0}+${b1}*D${x}` : sel.id === 'temperature' ? `${b0}+${b1}*B${x}` : `${b0}+${b1}*B${x}+${b2}*C${x}`;
      s.set(rr, 8, { f: `IF(H${x}=1,${expr},"")`, v: d.expectedKW ?? '' }, styles.num, '#,##0');
      s.set(rr, 9, { f: `IF(H${x}=1,E${x}-I${x},"")`, v: d.expectedKW === null ? '' : d.kW - d.expectedKW }, styles.num, '#,##0');
    });
  } else {
    for (const n of w.notes) s.set(r++, 0, n, styles.wrap);
  }
  s.widths = [34, 11, 12, 14, 12, 12, 10, 14, 12, 12];
  return s;
}

// ---------------------------------------------------------------- annual projection sheet
/** Hourly method with live formulas (Stull wet-bulb → kWh → TR·h → monthly/annual totals); daily method as results. */
function annualSheet(a: AnalysisResult) {
  const p = a.annual!;
  const h = p.hourly!;
  const s = new Sheet('Annual Projection');
  const MON = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  s.set(0, 0, 'Annual projection – typical-year weather', styles.title);
  s.set(1, 0, `Typical year: ${p.typicalFile}. Driver: ${p.predictorLabel}. Yellow cells are inputs; change the coefficients or the scenario and the sheet recalculates.`, styles.sub);
  const T0 = 44; // first row of the hourly table (0-based header row)
  const last = T0 + 1 + p.typical.length; // 1-based last row
  const first = T0 + 2;
  const rng = (c: string) => `$${c}$${first}:$${c}$${last}`;
  // coefficients (rows 4-8, 1-based 5-9)
  s.set(3, 0, 'Hourly regression (fitted on the logged hours)', styles.section); s.set(3, 1, '', styles.section);
  s.set(4, 0, 'Energy slope (kWh per driver unit)', styles.label); s.set(4, 1, h.energyModel.slope, styles.input, '0.0000');
  s.set(5, 0, 'Energy intercept (kWh)', styles.label); s.set(5, 1, h.energyModel.intercept, styles.input, '0.000');
  s.set(6, 0, 'Load slope (TR·h per kWh)', styles.label); s.set(6, 1, h.loadModel.slope, styles.input, '0.000000');
  s.set(7, 0, 'Load intercept (TR·h)', styles.label); s.set(7, 1, h.loadModel.intercept, styles.input, '0.000');
  s.set(8, 0, 'Scale to 8,760 h', styles.label); s.set(8, 1, 8760 / p.typical.length, styles.input, '0.0000');
  s.set(9, 0, 'R² (energy vs driver / load vs energy)', styles.label); s.set(9, 1, h.energyModel.r2, styles.num, '0.000'); s.set(9, 2, h.loadModel.r2, styles.num, '0.000');
  // results
  s.set(11, 0, 'Annual results (hourly method)', styles.section); s.set(11, 1, '', styles.section);
  s.set(12, 0, 'Annual energy (kWh/yr)', styles.label); s.set(12, 1, { f: `SUM(${rng('F')})*B9`, v: h.kWh }, styles.num, '#,##0');
  s.set(13, 0, 'Annual cooling (TR·h/yr)', styles.label); s.set(13, 1, { f: `SUM(${rng('G')})*B9`, v: h.trHours }, styles.num, '#,##0');
  s.set(14, 0, 'Plant efficiency (kW/TR)', styles.label); s.set(14, 1, { f: 'IF(B14>0,B13/B14,"")', v: h.kwPerTR }, styles.num, '0.000');
  // scenario
  s.set(16, 0, 'Savings scenario', styles.section); s.set(16, 1, '', styles.section);
  const sc = p.scenario;
  s.set(17, 0, 'Proposed efficiency (kW/TR)', styles.label); s.set(17, 1, a.settings.annualProposedKwPerTR, styles.input, '0.000');
  s.set(18, 0, 'Safety factor (%)', styles.label); s.set(18, 1, a.settings.annualSafetyPct, styles.input, '0');
  s.set(19, 0, 'Tariff (per kWh)', styles.label); s.set(19, 1, a.settings.tariff, styles.input, '0.000');
  s.set(20, 0, 'Proposed consumption (kWh/yr)', styles.label); s.set(20, 1, { f: 'IF(B18>0,B14*B18*(1+B19/100),"")', v: sc?.proposedKWh ?? '' }, styles.num, '#,##0');
  s.set(21, 0, 'Annual saving (kWh/yr)', styles.label); s.set(21, 1, { f: 'IF(B18>0,B13-B21,"")', v: sc?.savingKWh ?? '' }, styles.num, '#,##0');
  s.set(22, 0, 'Annual saving (%)', styles.label); s.set(22, 1, { f: 'IF(AND(B18>0,B13>0),B22/B13,"")', v: sc ? sc.savingPct / 100 : '' }, styles.num, '0.0%');
  s.set(23, 0, 'Annual saving (cost)', styles.label); s.set(23, 1, { f: 'IF(B18>0,B22*B20,"")', v: sc?.savingCost ?? '' }, styles.num, '#,##0');
  // monthly
  s.set(25, 0, 'Monthly (hourly method)', styles.section); for (let c = 1; c < 4; c++) s.set(25, c, '', styles.section);
  s.head(26, 0, ['Month', 'kWh', 'TR·h', 'kW/TR']);
  MON.forEach((mn, i) => {
    const r = 27 + i, x = r + 1;
    const m = h.monthly[i];
    s.set(r, 0, mn, styles.label);
    s.set(r, 1, { f: `SUMIF(${rng('H')},${i + 1},${rng('F')})*$B$9`, v: m.kWh }, styles.num, '#,##0');
    s.set(r, 2, { f: `SUMIF(${rng('H')},${i + 1},${rng('G')})*$B$9`, v: m.trHours }, styles.num, '#,##0');
    s.set(r, 3, { f: `IF(C${x}>0,B${x}/C${x},"")`, v: Number.isFinite(m.kwPerTR) ? m.kwPerTR : '' }, styles.num, '0.000');
  });
  // daily method (results)
  const d = p.daily;
  s.set(3, 5, 'Daily method (results)', styles.section); for (let c = 6; c < 9; c++) s.set(3, c, '', styles.section);
  if (d) {
    s.set(4, 5, 'Energy slope / intercept', styles.label); s.set(4, 6, d.energyModel.slope, styles.num, '0.0000'); s.set(4, 7, d.energyModel.intercept, styles.num, '0.0');
    s.set(5, 5, 'Load slope / intercept', styles.label); s.set(5, 6, d.loadModel.slope, styles.num, '0.000000'); s.set(5, 7, d.loadModel.intercept, styles.num, '0.0');
    s.set(6, 5, 'R² (energy / load)', styles.label); s.set(6, 6, d.energyModel.r2, styles.num, '0.000'); s.set(6, 7, d.loadModel.r2, styles.num, '0.000');
    s.set(7, 5, 'Annual energy (kWh/yr)', styles.label); s.set(7, 6, d.kWh, styles.num, '#,##0');
    s.set(8, 5, 'Annual cooling (TR·h/yr)', styles.label); s.set(8, 6, d.trHours, styles.num, '#,##0');
    s.set(9, 5, 'Plant efficiency (kW/TR)', styles.label); s.set(9, 6, d.kwPerTR, styles.num, '0.000');
    if (p.methodDifferencePct !== null) { s.set(10, 5, 'Daily vs hourly energy', styles.label); s.set(10, 6, p.methodDifferencePct / 100, styles.num, '0.0%'); }
  } else s.set(4, 5, 'Not available (needs complete logged days and a full typical year).', styles.body);
  p.notes.forEach((n, i) => s.set(14 + i, 5, n, styles.body));
  // hourly table
  s.head(T0, 0, ['Hour (typical year)', 'Temp °C', 'RH %', 'Enthalpy kJ/kg', 'Driver', 'kWh', 'TR·h', 'Month']);
  s.set(T0 - 1, 0, 'Typical-year hours', styles.section); for (let c = 1; c < 8; c++) s.set(T0 - 1, c, '', styles.section);
  p.typical.forEach((x, i) => {
    const rr = T0 + 1 + i, n = rr + 1;
    const drv = predictorValue(p.predictor, x) as number;
    const kwh = Math.max(0, h.energyModel.slope * drv + h.energyModel.intercept);
    const tr = Math.max(0, h.loadModel.slope * kwh + h.loadModel.intercept);
    const R = `MIN(MAX(C${n},1),100)`;
    const driver = p.predictor === 'temperature' ? `B${n}` : p.predictor === 'enthalpy' ? `D${n}` : `B${n}*ATAN(0.151977*SQRT(${R}+8.313659))+ATAN(B${n}+${R})-ATAN(${R}-1.676331)+0.00391838*${R}^1.5*ATAN(0.023101*${R})-4.686035`;
    s.set(rr, 0, toExcelDate(x.ts), styles.num, DATE_FMT);
    s.set(rr, 1, x.tempC, styles.num, '0.0'); s.set(rr, 2, x.rh ?? '', styles.num, '0'); s.set(rr, 3, x.enthalpy ?? '', styles.num, '0.0');
    s.set(rr, 4, { f: driver, v: drv }, styles.num, '0.00');
    s.set(rr, 5, { f: `MAX(0,$B$5*E${n}+$B$6)`, v: kwh }, styles.num, '#,##0');
    s.set(rr, 6, { f: `MAX(0,$B$7*F${n}+$B$8)`, v: tr }, styles.num, '#,##0');
    s.set(rr, 7, { f: `MONTH(A${n})`, v: new Date(x.ts).getUTCMonth() + 1 }, styles.num, '0');
  });
  s.widths = [38, 14, 14, 16, 12, 12, 12, 8];
  return s;
}

// ---------------------------------------------------------------- CDD sheet
function cddSheet(a: AnalysisResult) {
  const c = a.cdd!;
  const s = new Sheet('CDD Daily');
  s.set(0, 0, 'Cooling degree days – daily regression & weather normalisation', styles.title);
  s.set(1, 0, `Weather file: ${c.fileName} (${c.source === 'cdd' ? 'CDD supplied' : `CDD from temperature, base ${a.settings.cddBaseTemp} °C`}). Days enter the regression when ≥ ${Math.round(a.settings.cddMinCoverage * 100)} % logged. Model: daily kWh = b0 + b1·CDD.`, styles.sub);
  const em = c.energyModel;
  const lm = c.loadModel;
  s.head(3, 0, ['Model', 'Value', 'Unit / note']);
  const row = (r: number, label: string, v: number | string | { f: string; v: number | string }, z: string, note = '') => { s.set(r, 0, label, styles.label); s.set(r, 1, v, typeof v === 'string' ? styles.body : styles.num, z); s.set(r, 2, note, styles.body); };
  if (em) {
    row(4, 'Base load b0', em.coefs[0].value, '#,##0.0', 'kWh/day at CDD = 0');
    row(5, 'Weather slope b1', em.coefs[1].value, '#,##0.00', 'kWh per CDD');
    row(6, 'R²', em.r2, '0.0000'); row(7, 'CV(RMSE)', em.cv / 100, '0.00%', `limit ${em.guideline14.cvLimit} % (daily data)`);
    row(8, 'NMBE', em.nmbe / 100, '0.000%', `limit ±${em.guideline14.nmbeLimit} %`);
    row(9, 'Guideline 14', em.guideline14.pass ? 'PASS' : 'FAIL', '@');
    s.set(9, 1, em.guideline14.pass ? 'PASS' : 'FAIL', chip(em.guideline14.pass ? 'PASS' : 'FAIL'));
    row(10, 'b1 95 % CI', `${em.coefs[1].ciLow.toFixed(2)} … ${em.coefs[1].ciHigh.toFixed(2)}`, '@', `n = ${em.n} days`);
  } else row(4, 'Regression', 'not computed', '@', c.notes.filter((n) => /Only|hardly|could not/.test(n)).join(' '));
  if (lm) { row(11, 'TR·h base c0', lm.coefs[0].value, '#,##0.0', 'TR·h/day at CDD = 0'); row(12, 'TR·h slope c1', lm.coefs[1].value, '#,##0.00', 'TR·h per CDD'); }
  if (em && lm) {
    row(13, 'Reference CDD', c.refCdd, '0.00', c.refLabel);
    const kwh = em.coefs[0].value + em.coefs[1].value * c.refCdd;
    const trh = lm.coefs[0].value + lm.coefs[1].value * c.refCdd;
    row(14, 'Normalised energy', { f: 'B5+B6*B14', v: kwh }, '#,##0', 'kWh/day at the reference CDD');
    row(15, 'Normalised cooling', { f: 'B12+B13*B14', v: trh }, '#,##0', 'TR·h/day');
    row(16, 'Normalised plant kW/TR', { f: 'IF(B16>0,B15/B16,"")', v: trh > 0 ? kwh / trh : '' }, '0.000', 'weather-normalised efficiency');
    if (c.annual) row(17, 'Annual normalised energy', { f: `365*B5+B6*${c.annual.typicalCdd}`, v: c.annual.kWh }, '#,##0', `typical year ${c.annual.typicalCdd} CDD`);
  }
  const h0 = 19;
  s.head(h0, 0, ['Date', 'CDD', 'Hours logged', 'Coverage', 'Chiller kWh', 'Aux kWh', 'Total kWh', 'TR·h', 'kW/TR', 'Used', 'Expected kWh', 'Residual kWh', 'Residual %']);
  c.days.forEach((d, i) => {
    const r = h0 + 1 + i;
    const x = r + 1;
    s.set(r, 0, toExcelDate(d.day), styles.num, 'yyyy-mm-dd');
    s.set(r, 1, d.cdd ?? '', styles.num, '0.00'); s.set(r, 2, d.hoursLogged, styles.num, '0.0'); s.set(r, 3, { f: `C${x}/24`, v: d.coverage }, styles.num, '0%');
    s.set(r, 4, d.chillerKWh, styles.num, '#,##0'); s.set(r, 5, d.auxKWh, styles.num, '#,##0');
    s.set(r, 6, { f: `E${x}+F${x}`, v: d.kWh }, styles.num, '#,##0'); s.set(r, 7, d.trHours, styles.num, '#,##0');
    s.set(r, 8, { f: `IF(H${x}>0,G${x}/H${x},"")`, v: d.trHours > 0 ? d.kWh / d.trHours : '' }, styles.num, '0.000');
    s.set(r, 9, d.used ? 1 : 0, styles.num, '0');
    if (em) {
      s.set(r, 10, { f: `IF(J${x}=1,$B$5+$B$6*B${x},"")`, v: d.expectedKWh ?? '' }, styles.num, '#,##0');
      s.set(r, 11, { f: `IF(J${x}=1,G${x}-K${x},"")`, v: d.residualKWh ?? '' }, styles.num, '#,##0');
      s.set(r, 12, { f: `IF(J${x}=1,L${x}/K${x},"")`, v: d.expectedKWh ? (d.residualKWh as number) / d.expectedKWh : '' }, styles.num, '0.0%');
    }
  });
  s.widths = [24, 11, 12, 10, 12, 10, 12, 11, 9, 7, 13, 13, 11];
  return s;
}

// ---------------------------------------------------------------- Logger sheets
function loggerSummarySheet(list: { data: LoggerData; an: LoggerAnalysis }[], primary = false) {
  const s = new Sheet(primary ? 'Summary' : 'Logger Summary');
  s.set(0, 0, primary ? 'Chiller Power Profile' : 'Fluke logger summary', styles.title);
  s.set(1, 0, `${PRODUCT_NAME} ${APP_VERSION} · logger data stays on this computer`, styles.sub);
  let r = 3;
  for (const { data, an } of list) {
    s.set(r, 0, `${data.chiller}${data.serial ? ` · SN ${data.serial}` : ''}${data.model ? ` · Fluke ${data.model}` : ''}`, styles.section);
    for (let c = 1; c < 4; c++) s.set(r, c, '', styles.section);
    r++;
    s.head(r++, 0, ['Metric', 'Value', 'Unit', 'Note']);
    const m = (l: string, v: number | string, u: string, z: string, note = '') => { s.set(r, 0, l, styles.label); s.set(r, 1, v, typeof v === 'number' ? styles.num : styles.body, z); s.set(r, 2, u, styles.body); s.set(r, 3, note, styles.body); r++; };
    m('Rows', an.rows, '', '#,##0', `${an.intervalMinutes} min interval · source unit ${an.sourceUnit}`);
    m('Power column', data.powerColumn, '', '@');
    m('Period', `${fmtTs(an.firstTs)} → ${fmtTs(an.lastTs)}`, '', '@');
    m('Total energy', an.totalKWh, 'kWh', '#,##0', 'Σ kW × interval');
    m('Running threshold', an.runningThresholdKW, 'kW', '#,##0.0', 'max(5 kW, 8 % of P99)');
    m('Running energy', an.runningKWh, 'kWh', '#,##0');
    m('Standby energy', an.standbyKWh, 'kWh', '#,##0');
    m('Running hours', an.runningHours, 'h', '#,##0.0');
    m('Logged time', an.loggedHours, 'h', '#,##0.0');
    m('Running share', an.runningShare, '%', '0.0%');
    m('Average running power', an.avgRunningKW, 'kW', '#,##0');
    m('P10 running power', an.p10KW, 'kW', '#,##0');
    m('P90 running power', an.p90KW, 'kW', '#,##0');
    m('Peak power', an.peakKW, 'kW', '#,##0', fmtTs(an.peakTs));
    m('Starts', an.starts, '', '0', `max ${an.maxStartsPerDay}/day · ${an.shortRuns} run(s) <30 min`);
    m('Longest run', an.longestRunHours, 'h', '#,##0.0');
    m('Standby power', an.standbyKW, 'kW', '#,##0.0');
    if (an.phaseAvgKW) {
      m('Phase L1 / L2 / L3', an.phaseAvgKW.map((v) => v.toFixed(0)).join(' / '), 'kW', '@', 'average while running');
      m('Phase deviation', (an.phaseDeviationPct ?? 0) / 100, '%', '0.0%', 'max |Pi − mean| / mean');
    }
    if (data.energyKWhFromColumn !== undefined) m('Energy per logger counter', data.energyKWhFromColumn, 'kWh', '#,##0', data.energyColumn);
    for (const n of data.notes) s.set(r++, 0, `• ${n}`, styles.sub);
    r++;
    if (an.flags.length) {
      s.head(r++, 0, ['Status', 'Flag', 'Detail']);
      for (const f of an.flags) { s.set(r, 0, f.status, chip(f.status)); s.set(r, 1, f.title, styles.label); s.set(r, 2, f.text, styles.wrap); r++; }
    }
    r += 2;
  }
  s.widths = [30, 26, 14, 60];
  return s;
}
function loggerFindingsSheet(list: { data: LoggerData; an: LoggerAnalysis }[]) {
  const s = new Sheet('Findings');
  s.set(0, 0, 'Logger findings', styles.title);
  s.head(2, 0, ['Chiller', 'Status', 'Finding', 'Detail']);
  let r = 3;
  for (const { an } of list) {
    if (!an.flags.length) { s.row(r, 0, [an.chiller, 'OK', 'No issues flagged', ''], styles.body); s.set(r, 1, 'OK', chip('OK')); r++; }
    for (const f of an.flags) { s.set(r, 0, an.chiller, styles.body); s.set(r, 1, f.status, chip(f.status)); s.set(r, 2, f.title, styles.label); s.set(r, 3, f.text, styles.wrap); r++; }
  }
  s.widths = [12, 11, 28, 90];
  return s;
}
function loggerDataSheet(list: LoggerData[], ans: LoggerAnalysis[]) {
  const s = new Sheet('Logger Data');
  s.set(0, 0, 'Logger data (interval midpoints)', styles.title);
  s.set(1, 0, 'Running = kW above the threshold in column G. Energy = kW × interval.', styles.sub);
  s.head(3, 0, ['Midpoint', 'Chiller', 'kW', 'Interval h', 'kWh', 'Running', 'Threshold kW', 'L1 kW', 'L2 kW', 'L3 kW']);
  let r = 4;
  list.forEach((d, li) => {
    const thr = ans[li].runningThresholdKW;
    const samples = d.samples.length > MAX_DATA_ROWS ? thin(d.samples, MAX_DATA_ROWS) : d.samples;
    for (const smp of samples) {
      const x = r + 1;
      s.set(r, 0, toExcelDate(smp.ts), styles.num, DATE_FMT); s.set(r, 1, d.chiller, styles.body); s.set(r, 2, smp.kW, styles.num, '#,##0.0');
      s.set(r, 3, d.intervalMinutes / 60, styles.num, '0.0000');
      s.set(r, 4, { f: `C${x}*D${x}`, v: smp.kW * (d.intervalMinutes / 60) }, styles.num, '#,##0.00');
      s.set(r, 5, { f: `IF(C${x}>G${x},1,0)`, v: smp.kW > thr ? 1 : 0 }, styles.num, '0');
      s.set(r, 6, thr, styles.num, '#,##0.0');
      if (smp.phases) smp.phases.forEach((p, i) => s.set(r, 7 + i, Number.isFinite(p) ? p : '', styles.num, '#,##0.0'));
      r++;
    }
  });
  s.widths = [17, 10, 11, 10, 11, 9, 12, 10, 10, 10];
  return s;
}
function loggerCharts(d: LoggerData, an: LoggerAnalysis, cd: Sheet): ChartSpec[] {
  cd.set(0, 0, 'Chart Data', styles.title);
  const pts = loggerSeries(d, 2000);
  cd.head(3, 0, ['Midpoint', 'kW', 'Running threshold kW', 'Standby+running']);
  pts.forEach((p, i) => { cd.set(4 + i, 0, toExcelDate(p.ts), styles.num, DATE_FMT); cd.set(4 + i, 1, p.kW, styles.num, '#,##0.0'); cd.set(4 + i, 2, an.runningThresholdKW, styles.num, '#,##0.0'); });
  const n = pts.length;
  const ref = (c: number) => `${q(cd.name)}!$${colLetter(c)}$5:$${colLetter(c)}$${4 + n}`;
  const xs = pts.map((p) => toExcelDate(p.ts));
  const charts: ChartSpec[] = [{
    title: `${d.chiller} – power profile`, type: 'scatter', xTitle: 'Date', yTitle: 'kW', xFormat: 'dd-mmm', yFormat: '#,##0', yMin: 0, anchor: [0, 3, 12, 24],
    series: [
      { name: 'Active power (kW)', xRef: ref(0), yRef: ref(1), xVals: xs, yVals: pts.map((p) => p.kW), color: PAL[0], kind: 'line' },
      { name: 'Running threshold', xRef: ref(0), yRef: ref(2), xVals: xs, yVals: pts.map(() => an.runningThresholdKW), color: PAL[4], kind: 'line', dash: true },
    ],
  }];
  // duration curve
  const sorted = [...d.samples.map((s) => s.kW)].sort((x, y) => y - x);
  const dur = thin(sorted, 500);
  cd.head(3, 5, ['Hours exceeded', 'Power kW']);
  dur.forEach((v, i) => { cd.set(4 + i, 5, ((i / Math.max(1, dur.length - 1)) * sorted.length * d.intervalMinutes) / 60, styles.num, '#,##0.0'); cd.set(4 + i, 6, v, styles.num, '#,##0.0'); });
  const dref = (c: number) => `${q(cd.name)}!$${colLetter(c)}$5:$${colLetter(c)}$${4 + dur.length}`;
  charts.push({
    title: `${d.chiller} – power duration curve`, type: 'scatter', xTitle: 'Hours at or above', yTitle: 'kW', xFormat: '#,##0', yFormat: '#,##0', yMin: 0, anchor: [0, 25, 12, 46],
    series: [{ name: 'Power', xRef: dref(5), yRef: dref(6), xVals: dur.map((_, i) => ((i / Math.max(1, dur.length - 1)) * sorted.length * d.intervalMinutes) / 60), yVals: dur, color: PAL[1], kind: 'line' }],
  });
  cd.widths = [17, 11, 18, 4, 4, 14, 12];
  return charts;
}
